/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Dish {
  'name' : string,
  'instructions' : Array<string>,
  'nutritionSummary' : NutritionSummary,
  'photoReference' : string,
  'healthExplanation' : string,
  'ingredients' : Array<string>,
}
export interface NutritionSummary {
  'carbohydrates' : bigint,
  'sodium' : bigint,
  'fats' : bigint,
  'calories' : bigint,
  'protein' : bigint,
}
export interface _SERVICE {
  'addRecipe' : ActorMethod<
    [string, string, string, Array<string>, Array<string>, NutritionSummary],
    undefined
  >,
  'getFoodRecommendations' : ActorMethod<
    [bigint, bigint, Array<string>, bigint, bigint, Array<string>],
    Array<Dish>
  >,
  'getGreyZoneIngredients' : ActorMethod<[], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];